services:
  - type: web
    name: projet1-comparateur
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
      - key: BOXTAL_ACCESS_KEY
        sync: false
      - key: BOXTAL_SECRET_KEY
        sync: false
      - key: GEONAMES_USER
        sync: false